Repository Dev-FE-3/toy-project3-team4, pull requests merged in 2025-04, with the labels that each got.

#10 Feat: 조회수, 좋아요, 구독자수, 업로드 시간 포맷팅 함수 추가
  src/shared/util/format.ts
Labels: enhancement

#6 Design: header 디자인 2개 추가
  src/app/layout/Layout.tsx
  src/app/layout/aside/index.tsx
  src/app/layout/components/Header.tsx
  src/app/layout/mobile-view/components/Footer.tsx
  src/app/layout/mobile-view/components/Header.tsx
  src/app/layout/mobile-view/components/NavItem.tsx
  src/app/layout/mobile-view/index.tsx
  src/app/layout/mobile-view/type/INavItemProps.ts
Labels: enhancement

#11 Feat: 홈 페이지 구현
  src/feature/home/api/useChannelInfo.ts
  src/feature/home/api/useUserList.ts
  src/feature/home/api/useVideoList.ts
  src/feature/home/components/VideoItem.tsx
  src/feature/home/components/VideoItemSkeleton.tsx
  src/feature/home/hooks/useInfiniteScroll.ts
  src/feature/home/index.tsx
  src/feature/home/type/IUser.ts
  src/feature/home/type/IVideoTypes.ts
  src/shared/components/playlist/PlaylistInfo.tsx
  src/shared/components/playlist/PlaylistThumnail.tsx
  src/shared/components/playlist/type/IPlaylistInfoProps.ts
  src/shared/components/playlist/type/IPlaylistThumbnailProps.ts
  src/shared/components/video/ChannelAvatar.tsx
  src/shared/components/video/VideoInfo.tsx
  src/shared/components/video/VideoThumnail.tsx
  src/shared/components/video/type/IChannelAvatarProps.ts
  src/shared/components/video/type/IVideoInfoProps.ts
  src/shared/components/video/type/IVideoThumbnailProps.ts
  src/shared/style/global.css
  src/shared/util/youtube.ts
Labels: enhancement

#3 Feat: 플레이리스트 화면 디자인
  package-lock.json
  package.json
  src/app/routes/routes.tsx
  src/feature/playlist/api/usePlayList.ts
  src/feature/playlist/components/PlayListVideoItem.tsx
  src/feature/playlist/components/PlaylistFullModal.tsx
  src/feature/playlist/components/PlaylistHeader.tsx
  src/feature/playlist/components/PlaylistMiniModal.tsx
  src/feature/playlist/components/PlaylistPlayer.tsx
  src/feature/playlist/components/PlaylistTestPage.tsx
  src/feature/playlist/components/VideoDetailPage.tsx
  src/feature/playlist/hooks/usePlaylist.ts
  src/feature/playlist/index.tsx
  src/feature/playlist/mock/PlaylistMock.ts
  src/feature/playlist/services/fetchPlaylist.ts
  src/feature/playlist/types/IPlayList.ts
  src/feature/playlist/util/scroll.css
  src/shared/store/playlist/usePlaylistStore.ts
Labels: enhancement

#14 Feat: 검색 페이지 구현
  src/app/routes/routes.tsx
  src/feature/search/api/createPlaylistFromYouTube.ts
  src/feature/search/api/usePlaylistInfo.ts
  src/feature/search/api/usePlaylistVideos.ts
  src/feature/search/api/useSearch.ts
  src/feature/search/api/useVideoInfo.ts
  src/feature/search/components/SearchPlaylistItem.tsx
  src/feature/search/components/SearchTypeButtons.tsx
  src/feature/search/components/SearchVideoItem.tsx
  src/feature/search/index.tsx
  src/feature/search/service/handleSearchParams.ts
  src/feature/search/type/IPlaylistResultTypes.ts
  src/feature/search/type/ISearchResultItemTypes.ts
  src/feature/search/type/PlaylistCreationStatus.ts
  src/feature/search/type/SearchParams.ts
  src/feature/search/type/SearchType.ts
  src/feature/search/type/SearchTypeButtonProps.ts
  src/shared/components/alert/Alert.tsx
  src/shared/util/youtube.ts
Labels: enhancement

#21 Feat: 팔로잉 페이지 구현
  public/image/download/empty-user.svg
  src/app/routes/routes.tsx
  src/feature/follow/api/useFollowingChannels.ts
  src/feature/follow/api/useFollowingVideos.ts
  src/feature/follow/components/FollowingFeed.tsx
  src/feature/follow/components/FollowingList.tsx
  src/feature/follow/components/FollowingThumbnail.tsx
  src/feature/follow/components/UserNotFound.tsx
  src/feature/follow/hooks/usePagination.ts
  src/feature/follow/index.tsx
  src/feature/follow/type/IChannelData.ts
  src/feature/follow/type/IChannelVideo.ts
  src/feature/follow/type/IFollowingTypes.ts
  src/feature/home/hooks/useInfiniteScroll.ts
  src/feature/home/index.tsx
  src/feature/home/type/IVideoTypes.ts
  src/feature/search/index.tsx
  src/feature/search/type/ISearchResultItemTypes.ts
  src/shared/hooks/useInfiniteScroll.ts
  src/shared/type/IYouTubeTypes.ts
  src/shared/util/youtube.ts
Labels: enhancement

#22 Fix: data 타입 차이로 인한 상세페이지 이동 오류 수정
  src/feature/home/components/VideoItem.tsx
  src/shared/type/IYouTubeTypes.ts
Labels: bug

#24 Feat: 옵션 더보기 컴포넌트 추가 및 북마크 기능 연결
  src/feature/follow/components/FollowingFeed.tsx
  src/feature/home/components/VideoItem.tsx
  src/feature/home/hooks/useVideoState.ts
  src/feature/home/index.tsx
  src/feature/home/type/IVideoTypes.ts
  src/feature/search/components/SearchPlaylistItem.tsx
  src/feature/search/components/SearchVideoItem.tsx
  src/feature/search/index.tsx
  src/shared/components/more-options/MenuItem.tsx
  src/shared/components/more-options/MoreOptions.tsx
  src/shared/components/more-options/hooks/useToggle.ts
  src/shared/components/more-options/type/IMenuItem.ts
  src/shared/components/more-options/type/MoreOptionsProps.ts
  src/shared/components/more-options/utils/icon.tsx
Labels: enhancement

#34 Fix: 네비바 로그인한 사용자의 프로필 사진 동기화
  src/app/layout/mobile-view/components/Footer.tsx
Labels: bug, medium

#48 Fix: video page Issues
  src/feature/video/api/useUserImg.ts
  src/feature/video/components/Comment.tsx
  src/feature/video/components/CommentContainer.tsx
  src/feature/video/components/CommentForm.tsx
  src/feature/video/components/CommentList.tsx
  src/feature/video/components/FollowButton.tsx
  src/feature/video/index.tsx
  src/feature/video/type/IVideo.ts
Labels: bug

#54 Refactor: 구현되지 않은 페이지 Link 연결한 부분 삭제
  src/feature/follow/components/FollowingList.tsx
  src/feature/search/components/SearchTypeButtons.tsx
  src/shared/components/video/ChannelAvatar.tsx
Labels: bug

#52 Feat: 404 에러페이지 추가
  public/image/download/page-not-found.svg
  src/app/routes/routes.tsx
  src/shared/components/error/PageNotFound.tsx
Labels: enhancement

#55 Refactor: alert 사용하는 부분 수정
  src/app/layout/mobile-view/components/Header.tsx
  src/feature/search/components/SearchPlaylistItem.tsx
  src/shared/components/alert/Alert.tsx
  src/shared/components/alert/type/IAlertInfo.ts
Labels: enhancement

#56 Fix: 검색 시 비디오 제목 깨지는 현상
  src/shared/components/video/VideoInfo.tsx
  src/shared/components/video/util/decodeHtmlEntities.ts
Labels: bug

#60 Fix: 플레이리스트 저장 시 공개여부 데이터 타입 불일치 수정
  src/feature/search/api/createPlaylistFromYouTube.ts
Labels: bug, high

#67 Fix: Channel-issues
  src/feature/channel/api/usePlaylistInfo.ts
  src/feature/channel/api/useVideoInfo.ts
  src/feature/channel/components/PlayLisyItem.tsx
  src/feature/channel/components/TebMenu.tsx
  src/feature/channel/index.tsx
  src/feature/channel/tpye/IChannel.ts
Labels: bug, high

#68 Refactor: 디자인가이드 페이지 및 모달관련 수정
  src/app/routes/routes.tsx
  src/feature/design/Design.tsx
  src/shared/components/alert/Alert.tsx
  src/shared/components/newplaylist-modal/NewPlayListModal.tsx
  src/shared/components/newplaylist-modal/type/INewPlayListModalProps.tsx
  src/shared/components/playlist-modal/ModalManager.tsx
  src/shared/components/playlist-modal/PlayListModal.tsx
  src/shared/components/playlist-modal/type/IPlayListModalProps.tsx
Labels: high
